#BNF+IAT 1.0 UTF-8;
!grammar talker;


!slot <content>;


!start <begintalk>;
<begintalk>:<content>;


<content>:向前走!id(9)|向前走一步!id(10)|向后走!id(11)|向后走一步!id(11)|向后退!id(12)|向后退一步!id(13)|向左转!id(14)|向左旋转!id(15)|向右转!id(16)|向右旋转!id(17)|你好!id(1001)|你叫什么名字!id(1002)|你多大了!id(1003)|你几岁了!id(1004)|你来自哪里!id(1005)|介绍一下你自己!id(1006)|你自我介绍一下!id(1007)|介绍你自己!id(1008)|再见!id(1009)|很高兴见到你!id(1010)|你会做什么!id(1011)|你会什么!id(1012)|你是谁!id(1013)|快递!id(1014)|介绍重德智能!id(1015)|介绍一下重德智能!id(1015)|抬起左手!id(1018)|抬起右手!id(1019)|左手拿!id(1020)|右手拿!id(1021)|放下左手!id(1022)|放下右手!id(1023)|张开左手!id(1024)|张开右手!id(1025)|左手抓住!id(1026)|右手抓住!id(1027)|小德你回去吧!id(1030)|关闭!id(1031)|带我找方总!id(1029)|找方总!id(1030)|我想找方总!id(1031)|找常总!id(1029)|带我找常总!id(1030)|我想找常总!id(1031)|去常总办公室!id(1031)|去方总办公室!id(1031)|回到原点!id(1029)|回到起点!id(1029)|你回去吧!id(1029)|开启对话模式!id(1029)|进入对话模式!id(1029)|开启多轮交互模式!id(1029)|开启多轮交互!id(1029)|进入多轮交互模式!id(1029)|跟我聊天!id(1029)|陪我聊天!id(1029)|能和我聊会天吗!id(1029)|退出对话模式!id(1029)|退出多轮交互模式!id(1029)|退出多轮交互!id(1029)|关闭对话!id(1029)|关闭对话模式!id(1029)|关闭多轮交互模式!id(1029)|退出聊天!id(1029)|退出对话!id(1029)|开始对话!id(1029);
